services:
  - type: web
    name: aluno-api
    runtime: docker
    plan: free
    rootDir: backend
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-bitter-sunset-acgm06ap.sa-east-1.aws.neon.tech/neondb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: sua_senha_aqui
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
